---

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-setuptools
    - python3-venv
    - python3-pip
    - python3-dev
    - virtualenv
